import { useMemo, useState, type FormEvent } from 'react';
import { profile, projects } from '@/data/content';
import { useSystemStore, type Theme } from '@/os/stores/systemStore';

type BrowserPage = { value: string; kind: 'home' | 'project' | 'search' };
const homePage: BrowserPage = { value: 'portfolio://start', kind: 'home' };
export function SafariApp() {
  const [address, setAddress] = useState(homePage.value); const [history, setHistory] = useState<BrowserPage[]>([homePage]); const [historyIndex, setHistoryIndex] = useState(0); const page = history[historyIndex];
  const go = (next: BrowserPage) => { const stack = [...history.slice(0, historyIndex + 1), next]; setHistory(stack); setHistoryIndex(stack.length - 1); setAddress(next.value); };
  const navigate = (event: FormEvent) => { event.preventDefault(); const value = address.trim(); if (!value || value === homePage.value) go(homePage); else { const project = projects.find((entry) => `${entry.name} ${entry.slug}`.toLowerCase().includes(value.toLowerCase())); go(project ? { value: project.slug, kind: 'project' } : { value, kind: 'search' }); } };
  const externalUrl = page.value.startsWith('http') ? page.value : `https://${page.value.replace(/^https?:\/\//, '')}`;
  return <div className="utility-app safari-app"><form className="browser-toolbar" onSubmit={navigate}><button type="button" aria-label="Back" disabled={historyIndex === 0} onClick={() => { setHistoryIndex((value) => value - 1); setAddress(history[historyIndex - 1].value); }}>‹</button><button type="button" aria-label="Forward" disabled={historyIndex === history.length - 1} onClick={() => { setHistoryIndex((value) => value + 1); setAddress(history[historyIndex + 1].value); }}>›</button><label><span>⌕</span><input value={address} onChange={(event) => setAddress(event.target.value)} aria-label="Safari address or search" /></label><button type="submit" aria-label="Go">↵</button></form>{page.kind === 'home' ? <section className="safari-home"><p>FAVOURITES</p><h1>{projects[0]?.name ?? 'Portfolio'}</h1><span>Browse work locally or open a destination in a new tab.</span><div className="safari-favourites"><button type="button" onClick={() => go({ value: projects[0]?.slug ?? 'portfolio', kind: 'project' })}>Projects</button><button type="button" onClick={() => { setAddress(profile.socials.github); go({ value: profile.socials.github, kind: 'search' }); }}>GitHub</button><button type="button" onClick={() => { setAddress(profile.socials.linkedin); go({ value: profile.socials.linkedin, kind: 'search' }); }}>LinkedIn</button></div></section> : page.kind === 'project' ? <section className="browser-result"><span>◈</span><h2>{projects.find((project) => project.slug === page.value)?.name ?? 'Project'}</h2><p>{projects.find((project) => project.slug === page.value)?.description}</p><button type="button" onClick={() => go(homePage)}>Return to Start Page</button></section> : <section className="browser-result"><span>⌕</span><h2>{page.value}</h2><p>External sites open in their own browser tab; this keeps the portfolio desktop safe and avoids pretending an embedded site is live.</p><button type="button" onClick={() => window.open(externalUrl, '_blank', 'noopener,noreferrer')}>Open in browser</button></section>}</div>;
}

type Thread = { id: string; name: string; preview: string; messages: string[] };
const starterThreads: Thread[] = [{ id: 'portfolio', name: 'Portfolio', preview: 'Ready for the next build.', messages: ['The desktop is looking good.', 'Ready for the next build.'] }, { id: 'ideas', name: 'Ideas', preview: 'Save the best one.', messages: ['What should we build next?', 'Save the best one.'] }];
export function MessagesApp() {
  const [threads, setThreads] = useState(starterThreads); const [selected, setSelected] = useState(starterThreads[0].id); const [draft, setDraft] = useState(''); const active = threads.find((thread) => thread.id === selected) ?? threads[0];
  const send = (event: FormEvent) => { event.preventDefault(); const text = draft.trim(); if (!text) return; setThreads((current) => current.map((thread) => thread.id === selected ? { ...thread, preview: text, messages: [...thread.messages, text] } : thread)); setDraft(''); };
  const createThread = () => { const id = `thread-${Date.now()}`; setThreads((current) => [...current, { id, name: 'New conversation', preview: 'No messages yet', messages: ['Start a local conversation.'] }]); setSelected(id); };
  return <div className="utility-app messages-app"><aside><button className="messages-new" type="button" onClick={createThread}>＋ New Message</button>{threads.map((thread) => <button type="button" className={thread.id === selected ? 'selected' : ''} key={thread.id} onClick={() => setSelected(thread.id)}><strong>{thread.name}</strong><span>{thread.preview}</span></button>)}</aside><section><header><b>{active.name}</b><span>{active.messages.length} messages</span></header><div className="message-thread">{active.messages.map((message, index) => <p key={`${message}-${index}`} className={index % 2 ? 'outgoing' : ''}>{message}</p>)}</div><form onSubmit={send}><input value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="iMessage" aria-label="Message text" /><button type="submit" aria-label="Send message">↑</button></form></section></div>;
}

const locations = ['Portfolio HQ', 'Project studio', 'Coffee and code'];
export function MapsApp() { const [query, setQuery] = useState(locations[0]); const [route, setRoute] = useState(false); const result = useMemo(() => locations.find((location) => location.toLowerCase().includes(query.toLowerCase())) ?? 'No local place found', [query]); return <div className="utility-app maps-app"><section className="map-canvas"><span className="map-pin pin-one">●</span><span className={`map-pin pin-two${route ? ' routed' : ''}`}>●</span>{route && <span className="map-route">---╲<br />&nbsp;&nbsp;╲---</span>}<div className="map-card"><b>{result}</b><small>{route ? 'Route ready · 12 min' : 'Local portfolio map'}</small><button type="button" onClick={() => setRoute((value) => !value)}>{route ? 'Clear Route' : 'Directions'}</button></div></section><aside><label>⌕<input value={query} onChange={(event) => { setQuery(event.target.value); setRoute(false); }} aria-label="Search maps" placeholder="Search places" /></label><p>RECENT</p>{locations.map((location) => <button key={location} type="button" onClick={() => { setQuery(location); setRoute(false); }}>⌖ {location}</button>)}</aside></div>; }

const photoNames = ['Desktop study', 'Project interface', 'Night deploy', 'Sketchbook', 'Coffee break', 'Launch day'];
export function PhotosApp() { const [selected, setSelected] = useState(0); const [favorites, setFavorites] = useState<number[]>([]); const isFavourite = favorites.includes(selected); return <div className="utility-app photos-app"><header><b>Library</b><span>{photoNames.length} Photos · {favorites.length} Favorites</span></header><div className="photo-grid">{photoNames.map((name, index) => <button key={name} type="button" className={`photo-tile tile-${index}${selected === index ? ' selected' : ''}`} onClick={() => setSelected(index)}><span>{name}</span></button>)}</div><footer>Selected: {photoNames[selected]} <button type="button" onClick={() => setFavorites((current) => isFavourite ? current.filter((item) => item !== selected) : [...current, selected])}>{isFavourite ? '♥ Favorited' : '♡ Add to Favorites'}</button></footer></div>; }

const weekdays = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
export function CalendarApp() { const [monthOffset, setMonthOffset] = useState(0); const [selectedDay, setSelectedDay] = useState(22); const [events, setEvents] = useState(['Portfolio polish · 10:00', 'Frontend review · 15:00']); const [draft, setDraft] = useState(''); const date = new Date(2026, 8 + monthOffset, 1); const monthLabel = new Intl.DateTimeFormat(undefined, { month: 'long', year: 'numeric' }).format(date); const days = new Date(2026, 9 + monthOffset, 0).getDate(); const firstDay = (date.getDay() + 6) % 7; const addEvent = (event: FormEvent) => { event.preventDefault(); const text = draft.trim(); if (!text) return; setEvents((current) => [...current, `${text} · ${selectedDay} ${monthLabel.split(' ')[0]}`]); setDraft(''); }; return <div className="utility-app calendar-app"><header><button type="button" aria-label="Previous month" onClick={() => setMonthOffset((value) => value - 1)}>‹</button><h2>{monthLabel}</h2><button type="button" onClick={() => { setMonthOffset(0); setSelectedDay(22); }}>Today</button><button type="button" aria-label="Next month" onClick={() => setMonthOffset((value) => value + 1)}>›</button></header><div className="calendar-layout"><section className="calendar-grid"><div className="weekdays">{weekdays.map((day) => <span key={day}>{day}</span>)}</div><div className="days">{Array.from({ length: firstDay }, (_, index) => <span key={`blank-${index}`} />)}{Array.from({ length: days }, (_, index) => <button type="button" className={`${selectedDay === index + 1 ? ' selected-day' : ''}${monthOffset === 0 && index + 1 === 22 ? ' today' : ''}`} key={index} onClick={() => setSelectedDay(index + 1)}>{index + 1}</button>)}</div></section><aside><b>{selectedDay} {monthLabel.split(' ')[0].toUpperCase()} · UPCOMING</b>{events.map((item, index) => <p key={`${item}-${index}`}><i />{item}<button type="button" aria-label={`Remove ${item}`} onClick={() => setEvents((current) => current.filter((_, eventIndex) => eventIndex !== index))}>×</button></p>)}<form onSubmit={addEvent}><input value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Add event" aria-label="New calendar event" /><button type="submit">+</button></form></aside></div></div>; }

const files = { 'profile.ts': `export const profile = {\n  focus: 'useful products',\n  stack: ['React', 'TypeScript'],\n  status: 'building'\n};\n\nconsole.log(profile);`, 'README.md': '# Portfolio\n\nA local interactive desktop portfolio.\n\n## Commands\n\nUse the Dock, Finder, Spotlight, or Terminal to explore.' };
export function VSCodeApp() { const [selectedFile, setSelectedFile] = useState<keyof typeof files>('profile.ts'); const [content, setContent] = useState(files); const [saved, setSaved] = useState<Record<string, boolean>>({ 'profile.ts': true, 'README.md': true }); const change = (value: string) => { setContent((current) => ({ ...current, [selectedFile]: value })); setSaved((current) => ({ ...current, [selectedFile]: false })); }; return <div className="utility-app vscode-app"><aside><b>EXPLORER</b><button type="button" className="active">▾ portfolio</button><button type="button" onClick={() => setSelectedFile('profile.ts')} className={selectedFile === 'profile.ts' ? 'selected-file' : ''}>└ profile.ts</button><button type="button" onClick={() => setSelectedFile('README.md')} className={selectedFile === 'README.md' ? 'selected-file' : ''}>└ README.md</button></aside><section><header><span>{selectedFile}{saved[selectedFile] ? '' : ' •'}</span><button type="button" onClick={() => setSaved((current) => ({ ...current, [selectedFile]: true }))}>Save</button></header><textarea value={content[selectedFile]} onChange={(event) => change(event.target.value)} spellCheck={false} aria-label="Code editor" /><footer>{saved[selectedFile] ? 'Saved locally' : 'Unsaved changes'} <span>{selectedFile.endsWith('.md') ? 'Markdown' : 'TypeScript'}</span></footer></section></div>; }

export function XApp() { const [posts, setPosts] = useState(['Building a portfolio that feels like a desktop.', 'Small interactions make interfaces memorable.']); const [draft, setDraft] = useState(''); const [tab, setTab] = useState<'Home' | 'Explore' | 'Bookmarks'>('Home'); const [bookmarks, setBookmarks] = useState<number[]>([]); const post = (event: FormEvent) => { event.preventDefault(); const text = draft.trim(); if (!text) return; setPosts((current) => [text, ...current]); setDraft(''); setTab('Home'); }; const shownPosts = tab === 'Bookmarks' ? posts.filter((_, index) => bookmarks.includes(index)) : posts; return <div className="utility-app x-app"><aside><b>𝕏</b>{(['Home', 'Explore', 'Bookmarks'] as const).map((item) => <button type="button" key={item} className={tab === item ? 'active' : ''} onClick={() => setTab(item)}>{item}</button>)}</aside><section><header><h2>{tab}</h2></header>{tab !== 'Bookmarks' && <form onSubmit={post}><textarea value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="What is happening?" aria-label="Compose post" /><button type="submit">Post</button></form>}{tab === 'Explore' && <p className="x-discovery">Explore locally saved thoughts and project updates.</p>}<div className="feed">{shownPosts.length ? shownPosts.map((item, index) => { const originalIndex = tab === 'Bookmarks' ? posts.indexOf(item) : index; const marked = bookmarks.includes(originalIndex); return <article key={`${item}-${originalIndex}`}><b>{profile.name}</b><span>@portfolio · now</span><p>{item}</p><button type="button" onClick={() => setBookmarks((current) => marked ? current.filter((itemIndex) => itemIndex !== originalIndex) : [...current, originalIndex])}>{marked ? '♥ Bookmarked' : '♡ Bookmark'}</button></article>; }) : <p className="empty-state">No bookmarked posts yet.</p>}</div></section></div>; }

export function SettingsApp() { const theme = useSystemStore((state) => state.theme); const setTheme = useSystemStore((state) => state.setTheme); const [panel, setPanel] = useState('Appearance'); const [reducedMotion, setReducedMotion] = useState(false); const [indicators, setIndicators] = useState(true); const [notifications, setNotifications] = useState(true); const panels = ['Appearance', 'Desktop & Dock', 'Notifications', 'Privacy']; return <div className="utility-app settings-app"><aside><b>System Settings</b>{panels.map((item) => <button key={item} type="button" className={item === panel ? 'selected' : ''} onClick={() => setPanel(item)}>{item}</button>)}</aside><section>{panel === 'Appearance' && <><h2>Appearance</h2><p>Choose how this portfolio desktop looks locally.</p><div className="theme-options">{(['light', 'auto', 'dark'] as Theme[]).map((option) => <button key={option} type="button" className={theme === option ? 'selected' : ''} onClick={() => setTheme(option)}><span className={option} /><b>{option}</b></button>)}</div><Toggle label="Reduced motion preview" checked={reducedMotion} onChange={setReducedMotion} /></>}{panel === 'Desktop & Dock' && <><h2>Desktop & Dock</h2><p>Personalise interaction feedback for this browser-only desktop.</p><Toggle label="Show Dock indicators" checked={indicators} onChange={setIndicators} /><Toggle label="Auto-hide Dock" checked={false} onChange={() => undefined} disabled /></>}{panel === 'Notifications' && <><h2>Notifications</h2><p>External notifications are off; this portfolio never contacts a service without a future connection.</p><Toggle label="Local app notifications" checked={notifications} onChange={setNotifications} /></>}{panel === 'Privacy' && <><h2>Privacy</h2><p>Portfolio notes and preferences remain in this browser. No account or social data is being fetched yet.</p><Toggle label="Local storage enabled" checked onChange={() => undefined} disabled /></>}</section></div>; }
function Toggle({ label, checked, onChange, disabled = false }: { label: string; checked: boolean; onChange: (value: boolean) => void; disabled?: boolean }) { return <label className="settings-toggle"><span>{label}</span><input type="checkbox" checked={checked} disabled={disabled} onChange={(event) => onChange(event.target.checked)} /></label>; }

export function TrashApp() { const [items, setItems] = useState(['old-concept.png', 'draft-ideas.txt']); return <div className="utility-app trash-app"><header><h2>Trash</h2><button type="button" onClick={() => setItems([])} disabled={!items.length}>Empty</button></header>{items.length ? <div>{items.map((item) => <button type="button" key={item} onClick={() => setItems((current) => current.filter((entry) => entry !== item))}>▱<span>{item}</span><small>Remove</small></button>)}</div> : <p className="empty-state">Trash is empty</p>}</div>; }
